name: Download Quickstart script
description: Downloads https://get.konghq.com/quickstart
runs:
  using: composite
  steps:
    - name: Donwload script
      shell: bash
      run: |
        curl -Ls get.konghq.com/quickstart -o quickstart.sh
        chmod +x quickstart.sh
