name: Install deps
runs:
  using: composite
  steps:
    - name: Set up Ruby
      shell: bash
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
