name: Run Kong OSS
inputs:
  kong-image-tag:
    required: true
    description: |
      Kong Docker image tag to run, 3.6.1.
  kong-image-name:
    description: |
      Kong Docker image name to use, e.g. kong-gateway, kong-gateway-dev.

runs:
  using: composite
  steps:
    - name: Download quickstart script
      uses: ./.github/reusable-steps/download-quickstart-script
    - name: Run Kong
      shell: bash
      env:
        KONG_PLUGINS: 'bundled'
        KONG_IMAGE_TAG: ${{ inputs.kong-image-tag }}
        KONG_IMAGE_NAME: ${{ inputs.kong-image-name || 'kong' }}
      run: |
        ./quickstart.sh  -e "KONG_PLUGINS" -e "KONG_IMAGE_TAG" -e "KONG_IMAGE_NAME"
