name: Copy Latest Schemas
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: |
          Kong Gateway release, e.x. 3.4.x.
          Used by some commands for storing files in the corresponding folder.

jobs:
  copy-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/reusable-steps/install-deps
      - name: Run copy_schemas
        run: |
          bundle exec ./plugins copy_schemas --version=${{ github.event.inputs.version }} --plugins $(ls ./schemas) --verbose
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          title: "Copy latest schemas to ${{ github.event.inputs.version }}"
          branch: copy-latest-schemas
          commit-message: "Copy latest schemas to ${{ github.event.inputs.version }}"
          delete-branch: true
          add-paths: |
            ./schemas/*
